MODEL:
  Z_SIZE: 8
  BATCH_SIZE: 16
  NB_INPUT_LAYER: 2
  NB_OUTPUT_LAYER: 2
  STEEP_LAYER_SIZE: False
  EPOCH: 50
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.015
  NB_CORRUPTED: 1
DATASET:
  SHUFFLE: True
  SPLIT: [0.8, 0.2]
SEED: 27493045