MODEL:
  Z_SIZE: 11
  BATCH_SIZE: 32
  NB_INPUT_LAYER: 2
  NB_OUTPUT_LAYER: 2
  STEEP_LAYER_SIZE: True
  EPOCH: 50
  LEARNING_RATE: 0.0002
  WEIGHT_DECAY: 0.000001
  NB_CORRUPTED: 1
DATASET:
  NAME: "abalone"
  SHUFFLE: True
  SPLIT: [0.7, 0.3]
SEED: 27123045
EVALUATION:
  MODE: "TR"