MODEL:
  Z_SIZE: 11
  BATCH_SIZE: 64
  NB_INPUT_LAYER: 3
  NB_OUTPUT_LAYER: 3
  STEEP_LAYER_SIZE: True
  EPOCH: 2
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.000001
DATASET:
  NAME: "abalone"
  SHUFFLE: True
  SPLIT: [0.7, 0.3]
SEED: 27123045
EVALUATION:
  MODE: "TR"
PLOT:
  TRAINING_RMSE_PER_K: True
  VALIDATION_RMSE_PER_K: True
  FULL_RMSE: True
  PARTIAL_RMSE: True