MODEL:
  Z_SIZE: 9
  BATCH_SIZE: 32
  NB_INPUT_LAYER: 5
  NB_OUTPUT_LAYER: 5
  STEEP_LAYER_SIZE: False
  EPOCH: 50
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.001
  NB_CORRUPTED: 1
DATASET:
  NAME: "abalone"
  SHUFFLE: True
  SPLIT: [0.7, 0.3]
SEED: 27123045