MODEL:
  Z_SIZE: 11
  BATCH_SIZE: 64
  NB_INPUT_LAYER: 2
  NB_OUTPUT_LAYER: 2
  STEEP_LAYER_SIZE: True
  EPOCH: 100
  LEARNING_RATE: 0.00005
  WEIGHT_DECAY: 0.000001
  TRUNK_GRAD: True
DATASET:
  NAME: "abalone"
  SHUFFLE: True
  SPLIT: [0.7, 0.3]
SEED: 27123045
EVALUATION:
  MODE: "TR"
PLOT:
  TRAINING_ERROR_PER_K: True
  VALIDATION_ERROR_PER_K: True
  FULL_ERROR: True
  PARTIAL_ERROR: True