MODEL:
  Z_SIZE: 1536
  BATCH_SIZE: 64
  NB_INPUT_LAYER: 3
  NB_OUTPUT_LAYER: 3
  STEEP_LAYER_SIZE: False
  EPOCH: 25
  LEARNING_RATE: 0.01
  WEIGHT_DECAY: 0.001
  NB_CORRUPTED: 1
  TRUNK_GRAD: True
DATASET:
  NAME: "EMBEDDING"
  USED_CATEGORY: ["top", "bottom", "shoe"]
  EMBEDDING_SIZE: 512
  SHUFFLE: True
  SPLIT: [0.8, 0.2]
SEED: 27493045