MODEL:
  Z_SIZE: 1536
  BATCH_SIZE: 128
  NB_INPUT_LAYER: 4
  NB_OUTPUT_LAYER: 4
  STEEP_LAYER_SIZE: False
  EPOCH: 50
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.0001
  NB_CORRUPTED: 1
  TRUNK_GRAD: True
DATASET:
  NAME: "EMBEDDING"
  USED_CATEGORY: ["top", "bottom", "shoe"]
  EMBEDDING_SIZE: 512
  SHUFFLE: True
  SPLIT: [0.7, 0.3]
SEED: 27493045