USED_CATEGORY: ["top", "bottom", "shoe"]
MODEL:
  EMBEDDING_SIZE: 512
  Z_SIZE: 512
  BATCH_SIZE: 8
  NB_INPUT_LAYER: 5
  NB_OUTPUT_LAYER: 5
  STEEP_LAYER_SIZE: False
  EPOCH: 300
  LEARNING_RATE: 0.005
  WEIGHT_DECAY: 0.015