MODEL:
  Z_SIZE: 1024
  BATCH_SIZE: 8
  NB_INPUT_LAYER: 2
  NB_OUTPUT_LAYER: 2
  STEEP_LAYER_SIZE: False
  EPOCH: 600
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.015
  NB_CORRUPTED: 1
DATASET:
  USED_CATEGORY: ["top", "bottom", "shoe"]
  EMBEDDING_SIZE: 512
  SHUFFLE: True
  SPLIT: [0.8, 0.2]
SEED: 27493045