MODEL:
  Z_SIZE: 1536
  BATCH_SIZE: 32
  NB_INPUT_LAYER: 3
  NB_OUTPUT_LAYER: 3
  STEEP_LAYER_SIZE: False
  EPOCH: 200
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.01
  NB_CORRUPTED: 1
DATASET:
  NAME: "MODANET"
  USED_CATEGORY: ["top", "bottom", "shoe"]
  EMBEDDING_SIZE: 512
  SHUFFLE: True
  SPLIT: [0.8, 0.2]
SEED: 50493213