USED_CATEGORY: ["top", "bottom", "shoe"]
MODEL:
  EMBEDDING_SIZE: 512
  BATCH_SIZE: 1
  NB_INPUT_LAYER: 2
  NB_OUTPUT_LAYER: 2
  STEEP_LAYER_SIZE: False
  EPOCH: 200
  LEARNING_RATE: 0.1
  WEIGHT_DECAY: 0.1